#!/bin/bash

echo NO RUN!
exit 1


kubectl get -o=custom-columns=NAME:.metadata.name,LABELS:.metadata.labels svc



kubectl scale --replicas=3 deployment/herpderp
kubectl set image deployment azure-vote-front azure-vote-front=<acrLoginServer>/azure-vote-front:v2

kubectl run -i --tty --rm debug --image=busybox --restart=Never -- sh
kubectl run -i --tty --rm debug --image=ubuntu:latest --restart=Never -- sh

$(bx cs cluster-config <cluster-name>|grep "export KUBECONFIG")
