#!/bin/bash

echo NO RUN!
exit 1


kubectl get -o=custom-columns=NAME:.metadata.name,LABELS:.metadata.labels svc



kubectl scale --replicas=3 deployment/herpderp
kubectl set image deployment azure-vote-front azure-vote-front=<acrLoginServer>/azure-vote-front:v2

kubectl run -i --tty --rm debug --image=busybox --restart=Never -- sh
kubectl run -i --tty --rm debug --image=nginx --restart=Never -- sh
kubectl run -i --tty --rm debug --image=ubuntu:latest --restart=Never -- sh
kubectl run -i --tty poke2-`date +%s` --image=nibalizer/utilities --restart=Never -- sh

docker pull nibalizer/utilities
hashicorp/http-echo # 5678


$(bx cs cluster-config <cluster-name>|grep "export KUBECONFIG")

kubectl get deployment -o wide

wget https://storage.googleapis.com/kubernetes-release/release/v1.4.4/bin/linux/amd64/kubectl
 ./kubectl  --certificate-authority=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt  --server=${KUBERNETES_SERVICE_HOST} --token=/var/run/secrets/kubernetes.io/serviceaccount/token get pod

kubectl delete ns <namespace> --grace-period=0 --force
